"""Generate biquad coefficients (RBJ Audio EQ Cookbook style) for the EMG pipeline.

Outputs a C snippet with three biquad coefficient sets used by emg_pipeline.c:
  - HPF  Butterworth-style (Q=1/sqrt(2)) at 20 Hz
  - Notch (band-stop) at 50 Hz, Q=30
  - LPF  Butterworth-style (Q=1/sqrt(2)) at 150 Hz

Sample rate: 500 SPS.

We use the RBJ Audio EQ Cookbook formulas (a0-normalized direct-form II transposed):

  Common variables:
    w0    = 2*pi*f0 / fs
    alpha = sin(w0) / (2 * Q)

  HPF:
    b0 =  (1 + cos w0)/2,   b1 = -(1 + cos w0),   b2 =  (1 + cos w0)/2
    a0 =  1 + alpha,        a1 = -2*cos w0,       a2 =  1 - alpha

  Notch:
    b0 =  1,                b1 = -2*cos w0,       b2 =  1
    a0 =  1 + alpha,        a1 = -2*cos w0,       a2 =  1 - alpha

  LPF:
    b0 = (1 - cos w0)/2,    b1 =   1 - cos w0,    b2 = (1 - cos w0)/2
    a0 =  1 + alpha,        a1 = -2*cos w0,       a2 =  1 - alpha

After normalization by a0, the biquad processes input x[n] in DF2T form:
    y[n]   = b0*x[n] + s1
    s1_new = b1*x[n] - a1*y[n] + s2
    s2_new = b2*x[n] - a2*y[n]
"""
from __future__ import annotations
import math
from dataclasses import dataclass
from typing import Tuple


@dataclass
class Biquad:
    name: str
    b0: float
    b1: float
    b2: float
    a1: float  # a0-normalized
    a2: float

    def as_c_initializer(self) -> str:
        return (
            f"    /* {self.name} */\n"
            f"    {{ .b0 = {self.b0:.10f}f, .b1 = {self.b1:.10f}f, .b2 = {self.b2:.10f}f,\n"
            f"      .a1 = {self.a1:.10f}f, .a2 = {self.a2:.10f}f }}"
        )


def hpf(fs: float, fc: float, q: float, name: str) -> Biquad:
    w0 = 2.0 * math.pi * fc / fs
    cw = math.cos(w0)
    sw = math.sin(w0)
    alpha = sw / (2.0 * q)
    a0 = 1.0 + alpha
    return Biquad(
        name,
        b0=(1.0 + cw) / 2.0 / a0,
        b1=-(1.0 + cw) / a0,
        b2=(1.0 + cw) / 2.0 / a0,
        a1=(-2.0 * cw) / a0,
        a2=(1.0 - alpha) / a0,
    )


def lpf(fs: float, fc: float, q: float, name: str) -> Biquad:
    w0 = 2.0 * math.pi * fc / fs
    cw = math.cos(w0)
    sw = math.sin(w0)
    alpha = sw / (2.0 * q)
    a0 = 1.0 + alpha
    return Biquad(
        name,
        b0=(1.0 - cw) / 2.0 / a0,
        b1=(1.0 - cw) / a0,
        b2=(1.0 - cw) / 2.0 / a0,
        a1=(-2.0 * cw) / a0,
        a2=(1.0 - alpha) / a0,
    )


def notch(fs: float, f0: float, q: float, name: str) -> Biquad:
    w0 = 2.0 * math.pi * f0 / fs
    cw = math.cos(w0)
    sw = math.sin(w0)
    alpha = sw / (2.0 * q)
    a0 = 1.0 + alpha
    return Biquad(
        name,
        b0=1.0 / a0,
        b1=(-2.0 * cw) / a0,
        b2=1.0 / a0,
        a1=(-2.0 * cw) / a0,
        a2=(1.0 - alpha) / a0,
    )


def magnitude(b: Biquad, fs: float, freqs):
    """Return |H(f)| at the requested freqs."""
    out = []
    for f in freqs:
        w = 2.0 * math.pi * f / fs
        z = complex(math.cos(-w), math.sin(-w))
        num = b.b0 + b.b1 * z + b.b2 * (z ** 2)
        den = 1.0 + b.a1 * z + b.a2 * (z ** 2)
        out.append(abs(num / den))
    return out


def main():
    fs = 500.0
    hpf_b = hpf(fs, 20.0, q=1.0 / math.sqrt(2.0), name="HPF 20 Hz, Q=0.7071")
    notch_b = notch(fs, 50.0, q=30.0, name="Notch 50 Hz, Q=30")
    lpf_b = lpf(fs, 150.0, q=1.0 / math.sqrt(2.0), name="LPF 150 Hz, Q=0.7071")

    print("/* === Auto-generated by gen_biquad_coefs.py === */")
    print("/* fs = 500 SPS                                  */")
    print("/* Cascade: HPF20 -> Notch50 -> LPF150            */")
    print()
    print("static const emg_biquad_coef_t emg_biquad_coefs[EMG_BIQUAD_COUNT] = {")
    print(hpf_b.as_c_initializer() + ",")
    print(notch_b.as_c_initializer() + ",")
    print(lpf_b.as_c_initializer())
    print("};")
    print()

    # Frequency response sanity check.
    print("/* Sanity check (|H(f)| of cascade at key freqs): */")
    test_freqs = [0.5, 1, 5, 10, 20, 30, 40, 49, 50, 51, 60, 80, 100, 120, 150, 180, 200, 240]
    print("/*  f(Hz)   HPF      Notch    LPF      Cascade   */")
    for f in test_freqs:
        h = magnitude(hpf_b, fs, [f])[0]
        n = magnitude(notch_b, fs, [f])[0]
        l = magnitude(lpf_b, fs, [f])[0]
        c = h * n * l
        h_db = 20 * math.log10(h) if h > 0 else -120
        c_db = 20 * math.log10(c) if c > 0 else -120
        print(f"/*  {f:6.1f}  {h:7.4f}  {n:7.4f}  {l:7.4f}  {c:7.4f}  ({c_db:+.2f} dB) */")


if __name__ == "__main__":
    main()
